<h2>Suppression d'un contact</h2>

<form method="post">
    <p>Etes-vous sûr de vouloir supprimer <?=$this->escape($this->contact->getPrenom())?> <?=$this->escape($this->contact->getNom())?> ?</p>
    <p>
        <button type="submit" name="confirm" value="oui" class="btn btn-danger">Oui</button>
        <button type="submit" name="confirm" value="non" class="btn btn-default">Non</button>
    </p>
</form>