<?php $this->headTitle('Liste des contacts') ?>

<?php // $this->headLink()->appendStylesheet($this->baseUrl('css/index.css'))?>
<?php $this->headScript()->captureStart(); ?>
/*
setInterval(function() {
    document.body.style.background = (document.body.style.background === 'red') ? 'yellow' : 'red';
}, 200);
*/
<?php $this->headScript()->captureEnd(); ?>

<h2>Liste des contacts</h2>

<table class="table table-striped">
    <?php foreach ($this->contacts as $c) : ?>
    <tr>
        <td>
            <?=$this->escape($c->getPrenom())?> <?=$this->escape($c->getNom())?>
        </td>
        <td>
            <a href="<?=$this->url(['controller' => 'contact', 'action' => 'show', 'id' => $this->escape($c->getId())], null, true)?>" class="btn btn-default btn-xs">Afficher</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>