<?php $this->headTitle('Liste des contacts') ?>

<?php // $this->headLink()->appendStylesheet($this->baseUrl('css/index.css'))?>
<?php $this->headScript()->captureStart(); ?>
/*
setInterval(function() {
    document.body.style.background = (document.body.style.background === 'red') ? 'yellow' : 'red';
}, 200);
*/
<?php $this->headScript()->captureEnd(); ?>

<h2>Liste des contacts</h2>

<table class="table table-striped">
    <tr>
        <td>
            Jean Dupont
        </td>
        <td>
            <a href="<?=$this->url(['controller' => 'contact', 'action' => 'show', 'id' => 123], null, true)?>" class="btn btn-default btn-xs">Afficher</a>
        </td>
    </tr>
    <tr>
        <td>
            Eric Martin
        </td>
        <td>
            <a href="#">Afficher</a>
        </td>
    </tr>
</table>